apiVersion: apps/v1
kind: Deployment
metadata:
  name: gunxtech-ufin-omnichat-backoffice-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gunxtech-ufin-omnichat-backoffice-server
  template:
    metadata:
      labels:
        app: gunxtech-ufin-omnichat-backoffice-server
    spec:
      imagePullSecrets:
        - name: docker-registry-gunxtech
      containers:
        - name: gunxtech-ufin-omnichat-backoffice-server
          imagePullPolicy: IfNotPresent
          image: busybox
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: gunxtech-ufin-omnichat-backoffice-server-service
spec:
  type: ClusterIP
  selector:
    app: gunxtech-ufin-omnichat-backoffice-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
