import { Translation } from 'primeng/api';

export const PRIMENG_TH: Translation = {
  accept: 'ใช่',
  reject: 'ไม่',
  choose: 'เลือก',
  upload: 'อัปโหลด',
  cancel: 'ยกเลิก',
  clear: 'ล้าง',
  apply: 'ใช้',
  today: 'วันนี้',
  weekHeader: 'สัปดาห์',
  firstDayOfWeek: 0,
  dateFormat: 'yy-mm-dd',
  weak: 'อ่อน',
  medium: 'ปานกลาง',
  strong: 'แข็งแรง',
  passwordPrompt: 'กรอกรหัสผ่าน',
  emptyMessage: 'ไม่พบตัวเลือก',
  emptyFilterMessage: 'ไม่พบข้อมูล',
  emptySearchMessage: 'ไม่พบข้อมูล',
  emptySelectionMessage: 'ไม่ได้เลือกรายการ',
  searchMessage: '{0} ผลลัพธ์',
  selectionMessage: 'เลือก {0} รายการ',
  dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],
  dayNamesShort: ['อา.', 'จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.'],
  dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],
  monthNames: [
    'มกราคม',
    'กุมภาพันธ์',
    'มีนาคม',
    'เมษายน',
    'พฤษภาคม',
    'มิถุนายน',
    'กรกฎาคม',
    'สิงหาคม',
    'กันยายน',
    'ตุลาคม',
    'พฤศจิกายน',
    'ธันวาคม',
  ],
  monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],
  aria: {
    trueLabel: 'จริง',
    falseLabel: 'เท็จ',
    nullLabel: 'ไม่ได้เลือก',
    close: 'ปิด',
    previous: 'ก่อนหน้า',
    next: 'ถัดไป',
    pageLabel: 'หน้า {page}',
    firstPageLabel: 'หน้าแรก',
    lastPageLabel: 'หน้าสุดท้าย',
    nextPageLabel: 'หน้าถัดไป',
    prevPageLabel: 'หน้าก่อนหน้า',
    rowsPerPageLabel: 'แถวต่อหน้า',
    jumpToPageDropdownLabel: 'ไปที่หน้า',
    jumpToPageInputLabel: 'ไปที่หน้า',
    selectRow: 'เลือกแถว',
    unselectRow: 'ยกเลิกเลือกแถว',
    expandRow: 'ขยายแถว',
    collapseRow: 'ย่อแถว',
    editRow: 'แก้ไขแถว',
    saveEdit: 'บันทึก',
    cancelEdit: 'ยกเลิก',
  },
};
